repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
    - id: detect-private-key
    - id: end-of-file-fixer
    - id: trailing-whitespace

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.12.5
  hooks:
    - id: ruff-check
      args: [ --fix ]
    - id: ruff-format

- repo: https://github.com/gitleaks/gitleaks
  rev: v8.24.2
  hooks:
    - id: gitleaks

- repo: https://github.com/thlorenz/doctoc
  rev: v2.2.0
  hooks:
  - id: doctoc
